.build: &build
  stage: build
  tags:
    - docker
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker pull "$CACHE_FROM" || true
    - docker build -t "$CI_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG" --cache-from "$CACHE_FROM" --build-arg PHP_BASEIMAGE_VERION=$PHP_BASEIMAGE_VERION .
    - docker push "$CI_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG"

build-master:
  <<: *build
  variables:
    DOCKER_IMAGE_TAG: latest
    CACHE_FROM: $CI_REGISTRY_IMAGE:latest
  only:
    - master

build-next:
  <<: *build
  variables:
    DOCKER_IMAGE_TAG: next
    PHP_BASEIMAGE_VERION: 7.3.6
    CACHE_FROM: $CI_REGISTRY_IMAGE:next
  only:
    - next

build-next-7-2:
  <<: *build
  variables:
    DOCKER_IMAGE_TAG: next-7.2
    PHP_BASEIMAGE_VERION: 7.2.19
    CACHE_FROM: $CI_REGISTRY_IMAGE:next-7.2
  only:
    - next

build-tags:
  <<: *build
  variables:
    DOCKER_IMAGE_TAG: $CI_COMMIT_REF_NAME
    CACHE_FROM: $CI_REGISTRY_IMAGE:latest
  only:
    - tags
